# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /faq/:title
relative_permalinks: false

# Setup
title:            GT FAQ
tagline:          GT FAQ
description:      'Frequently Asked Questions about Georgia Tech'
url:              http://shoulditakethecredit.com
# baseurl:
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Algolia'
  url:            https://www.algolia.com/

# paginate:         5
# paginate_path: "/faq/page/num/"

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/danielms215/shoulditakethecredit/tree/gh-pages

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'GCD31PUTJI'
  index_name: 'gt_faq_index'
  read_only_api_key: '40a10525065cdd8c4e4d6834a29e4338'

  excluded_files:
    - 404.html
    - index.html
  attributesToIndex:
    - title
    - li
    - ol
    - ul
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6

future: true
