# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            GT FAQ
tagline:          'A Jekyll theme, with instant search'
description:      'Frequently Asked Questions about Georgia Tech'
url:              http://shoulditakethecredit.com/
destination:      _site/faq
# baseurl:          /
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Algolia'
  url:            https://www.algolia.com/

paginate:         5
paginate_path: "/faq/page/:num/"

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/danielms215/shoulditakethecredit

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'XQV74F7Q62'
  index_name: 'jekyll'
  read_only_api_key: '372379fb2611be972aa78fd1f72e3846'
  excluded_files:
    - 404.html
    - index.html

future: true
